//
// Created by skala on 17.5.17.
//

#ifndef UDPTASK_GLOBAL_CONST_H
#define UDPTASK_GLOBAL_CONST_H

#define DEFAULT_PORT 55555
#define PACKET_MAX_LEN 1024
#define BROADCAST_DELAY 1

#endif //UDPTASK_GLOBAL_CONST_H
